- src/elements/audio_block_format_objects.cpp
- tests/audio_block_format_objects_tests.cpp
Fixes #21; see that issue for discussion.
When `set<Cartesian>` was called, the position was cleared if `Cartesian` was defaulted.
This meant that this would have a default position rather than the one specified:
```cpp
AudioBlockFormatObjects(CartesianPosition(...), Cartesian(true))
```
Because `set<CartesianPosition>` also calls `set<Cartesian>`, this would have the same effect:
```cpp
AudioBlockFormatObjects(CartesianPosition(...))
```
To solve this, `set<>` for `Cartesian`, `SphericalPosition` and `CartesianPosition` now all just manipulate `cartesian_`, `sphericalPosition_` and `cartesianPosition_` directly, rather than calling each other.
This isn't the smallest change to fix this, but it does make it obviously correct -- there is no infinite recursion possible here, but before that …
> don't clear Objects position when Cartesian is set

- CHANGELOG.md
- include/adm/common_definitions.hpp
- resources/common_definitions.xml
- src/common_definitions.cpp
- tests/adm_common_definitions_tests.cpp
Dave mentioned that it would be useful to add similar common definition lookup functions for `HOA` as already exists for `DirectSpeakers`.
In the case of `audioPackFormat` the `HOA` packs have been included in the existing lookup table. For `audioTrackFormat` Tom suggested using the `order*order + order + degree` equation to find track Ids for `HOA`, as the track label doesn't carry any inherent meaning - as it does for `DirectSpeakers`.
`ADM_EXPORT` prefix added to `audioTrackFormatLookupTable ` and `audioPackFormatLookupTable` to allow them to be used in tests.
The common definitions xml has also been updated to most recent version.
> HOA common definitions lookup

- CHANGELOG.md
- include/adm/elements/audio_channel_format.hpp
- src/elements/audio_channel_format.cpp
assignId was very slow when adding lots of successive blocks. This is due to two nested loops; one in assignId to generate and ID, and one in idUsed to see if it is free. Therefore the time to perform this operation grew exponentially with the number of blocks added.
This PR has linear complexity since it simply refers to the ID of the preceding block to generate a new ID. It also checks that when blocks with ID's already assigned are added, they are one greater than the preceding block.
With this logic, it ensures that the counter portion of block ID's are consecutive as they are added. It does not enforce that the first block has a counter portion of 1, since this isn't necessarily the case in S-ADM.
> Improve logic and speed in AudioChannelFormat::assignId

- resources/common_definitions.xml
The pack AP_00010016 should refer to Side-Left and Side-Right, not Side-Right and Top-Centre as it does currently.
The error is also present in the excel sheet attached to BS.2094-1, but not the BS.2094-1 document itself.
> Fix common definition pack->channel reference error

- include/adm/elements/audio_channel_format.hpp
- include/adm/helper/element_range.hpp
- include/adm/utilities/comparator.hpp
- include/adm/utilities/lookup.hpp
- src/elements/audio_block_format_direct_speakers.cpp
- src/elements/audio_object.cpp
- src/elements/audio_pack_format.cpp
- src/elements/audio_programme.cpp
- src/elements/audio_stream_format.cpp
- tests/audio_channel_format_tests.cpp
This is mostly for `std::find`. I only had an issue in
`audio_block_format_direct_speakers.cpp`, but it's worth fixing
everywhere.
> include <algorithm> where it's used

- .github/workflows/coverage.yml
ubuntu-latest recently moved to 10.04 which broke the apt stage.
> Switch coverage build back to ubuntu 18

- .github/workflows/windows.yml
Following removal of boost from windows github runners on March 8th
> attempt to install boost dependency on windows

- .github/workflows/build.yml
- include/adm/elements/audio_block_format_binaural.hpp
- include/adm/elements/audio_block_format_direct_speakers.hpp
- include/adm/elements/audio_block_format_hoa.hpp
- include/adm/elements/audio_block_format_matrix.hpp
- include/adm/elements/audio_block_format_objects.hpp
- include/adm/elements/private/common_parameters.hpp
- src/elements/audio_block_format_binaural.cpp
- src/elements/audio_block_format_direct_speakers.cpp
- src/elements/audio_block_format_hoa.cpp
- src/elements/audio_block_format_matrix.cpp
- src/elements/audio_block_format_objects.cpp
- src/elements/common_parameters.cpp
should fix warnings in gcc; also cherry-picked the boost rational fix
> fixup headphone virtualise: only export template in one place

- include/adm/elements/audio_block_format_id.hpp
- include/adm/elements/audio_channel_format.hpp
- include/adm/elements/audio_channel_format_id.hpp
- include/adm/elements/audio_content.hpp
- include/adm/elements/audio_content_id.hpp
- include/adm/elements/audio_object.hpp
- include/adm/elements/audio_object_id.hpp
- include/adm/elements/audio_object_interaction.hpp
- include/adm/elements/audio_pack_format.hpp
- include/adm/elements/audio_pack_format_hoa.hpp
- include/adm/elements/audio_pack_format_id.hpp
- include/adm/elements/audio_programme.hpp
- include/adm/elements/audio_programme_id.hpp
- include/adm/elements/audio_stream_format.hpp
- include/adm/elements/audio_stream_format_id.hpp
- include/adm/elements/audio_track_format.hpp
- include/adm/elements/audio_track_format_id.hpp
- include/adm/elements/audio_track_uid.hpp
- include/adm/elements/audio_track_uid_id.hpp
- include/adm/elements/channel_lock.hpp
- include/adm/elements/frequency.hpp
- include/adm/elements/gain_interaction_range.hpp
- include/adm/elements/jump_position.hpp
- include/adm/elements/loudness_metadata.hpp
- include/adm/elements/object_divergence.hpp
- include/adm/elements/position.hpp
- include/adm/elements/position_interaction_range.hpp
- include/adm/elements/screen_edge_lock.hpp
- include/adm/elements/speaker_position.hpp
Add the ADM_EXPORT macro to `void print(std::ostream&) const;` declarations on all classes that have the method, to allow use from outside when compiled as a shared library.
> export print methods

- .github/workflows/build.yml
v10 only supports vcpkg.json rather than `vcpkgArguments` etc.
> pin run-vcpkg to v7

- include/adm/private/rapidxml_utils.hpp
- src/private/xml_parser.cpp
- tests/xml_parser_tests.cpp
previously this caused a segfault; a separate exception string is used as accidentally parsing an empty document seems like a reasonably common mistake
`inline` changes weren't necessary in the end, but it's a good idea anyway
> Fix segfault when there's no root node

- CHANGELOG.md
- include/adm/elements/gain.hpp
- tests/gain_tests.cpp
comparisons are not supported, but cases using these are probably easy to fix -- this is mostly to help users which rely on generic templated access to parameters
> add compatibility aliases to Gain class

- CHANGELOG.md
- config/admConfig.cmake.in
Since 56e7bc512823eb83b8ad48c24cbd3c41e817f4b0, the CMAKE_INSTALL_*
variables are used to set the install paths, however these are allowed
to be absolute paths, and this causes libadm_*DIRS to be set incorrectly
(to two concatenated absolute paths).
Fix this behaviour using GNUInstallDirs_get_absolute_install_dir, which
gives the same behaviour as just using CMAKE_INSTALL_* dirs directly.
This is useful mainly for split distribution packaging, where
development and run-time components are installed to completely separate
output directories
> support absolute directories in ADM_INSTALL_*

- include/adm/detail/id_map.hpp
- include/adm/private/rapidxml_utils.hpp
- submodules/rapidxml/rapidxml_print.hpp
- tests/enum_bitmask_options_tests.cpp
- tests/route_tracer_tests.cpp
fix a few warnings when compiling with gcc and clang
This misses a few warnings like this from gcc (not clang):
```
/home/thomasn/dev/audio/libadm/src/private/rapidxml_formatter.cpp:36:24: warning: ‘*((void*)(& cartesianPosition)+20).adm::detail::NamedType<float, adm::ZOffsetTag>::value_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
36 |           node.setValue(element.get());
|           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/home/thomasn/dev/audio/libadm/src/private/rapidxml_formatter.cpp:565:14: note: ‘*((void*)(& cartesianPosition)+20).adm::detail::NamedType<float, adm::ZOffsetTag>::value_’ was declared here
565 |         auto cartesianPosition =
|              ^~~~~~~~~~~~~~~~~
```
I can't quite figure out the cause of this. `boost::optional<T>::get` just asserts that …
> Fix warnings

- CHANGELOG.md
- src/elements/time.cpp
- tests/adm_time_tests.cpp
- tests/test_data/loudness_metadata.accepted.xml
- tests/test_data/simple_scene_default.accepted.xml
- tests/test_data/simple_scene_itu.accepted.xml
- tests/test_data/write_audio_programme.accepted.xml
- tests/test_data/write_object_attributes.accepted.xml
- tests/test_data/write_optional_defaults.accepted.xml
- tests/test_data/write_partially_specified_cartesian.accepted.xml
- tests/test_data/write_partially_specified_spherical.accepted.xml
- tests/test_data/write_specified_HOA_block.accepted.xml
- tests/test_data/write_specified_binaural_block.accepted.xml
- tests/test_data/write_specified_cartesian_speaker.accepted.xml
- tests/test_data/write_specified_spherical_speaker.accepted.xml
Decimal times are now written without trailing zeros past 5 decimal places. To interoperate with ADM parsers which don't support more than 5 digits, users should round times in the ADM document before writing.
closes #168
> remove trailing zeros from times up to 5dp

- CHANGELOG.md
- include/adm/private/xml_parser.hpp
- src/private/xml_parser.cpp
- tests/test_data/xml_parser/audio_object_complementary_audio_objects.xml
- tests/xml_parser_audio_object_tests.cpp
This is #175 with a couple of minor changes rebased and squashed:
- Formatted the code.
- Simplified the test: check that the complementary object reference is correct directly, in stead of checking it's in the vector with `std::find`.
> Fix parsing complementary objects (fixed up)

- include/adm/detail/id_assigner.hpp
- include/adm/utilities/id_assignment.hpp
- include/adm/utilities/object_creation.hpp
- src/elements/audio_channel_format.cpp
- src/elements/audio_pack_format.cpp
- src/utilities/id_assignment.cpp
- src/utilities/object_creation.cpp
- tests/adm_document_tests.cpp
- tests/helper/file_comparator.hpp
- tests/test_data/write_mixed_objects_and_structures.accepted.xml
- tests/test_data/write_simple_object_short_structure.accepted.xml
- tests/xml_writer_objects_creation_tests.cpp
Closes #181 
See issue ticket for more details
The approach has been to process ACFs stemming from ATUIDs in the `reassignAudioTrackUidIds`. If an ACF is found, apply an available ACF ID.
However, other ACF IDs (and ATF and ASF IDs) were applied in the `reassignAudioStreamFormatIds` function which just blindly applies IDs sequentially, because previously this was fine and logical to do - it was the only function assigning IDs to ACF elements. Therefore this function could now inadvertently assign the same ID to more than one ACF because there were no checks to see if the ID was available.
~~Therefore the new `getAvailableIdValue` function was written will find an available ID value to use with ACF, ATF and ASF groups. It ensures the ID value is available for all 3 element types so that …
> Support 2076-2-style structures in reassignIds

- include/adm/private/copy.hpp
- src/detail/id_assigner.cpp
- src/document.cpp
- src/private/copy.cpp
- src/utilities/copy.cpp
- tests/adm_document_tests.cpp
- tests/benchmarks.cpp
- tests/test_data/sink.xml
ID assignment was pretty slow for large documents
On my machine, adding 200 simple objects to a document took ~70ms, primarily due to the repeated document->lookup() calls. This adds a slightly more complex search for a free id, which reduces the cost of adding 200 objects to about 1.5ms. 
A 64 object document (more realistic) went from 2ms -> 200µs, which makes it more reasonable in an SADM context.
This should improve copying of medium/large docs (unless they're primarily common defs, which skipped the lookup anyway)
Probably slower for small documents, but should still be fast as then operating on small vectors.
Could improve further by keeping element vectors sorted on id, but that's a more intrusive change that might affect behaviour as elements would always get written out sorted by …
> Id assignment perf

- include/adm/detail/named_type_validators.hpp
- include/adm/elements/audio_object.hpp
- include/adm/utilities/element_io.hpp
The default clang-format has been updated on github's default runners, resulting in slightly different formatting for a few files. This PR applies the new formatting.
> Fix formatting for updated CI clang-format

- include/adm/elements/audio_channel_format.hpp
An audioChannelFormat in an S-ADM frame can contain a set of AudioBlockFormats with an initialiser block.
This is a special block that has a counter value of 0. It may also contain a run of contiguous blocks that start from some integer n > 1. This commit allows non-contiguous IDs to be added to a document for this case only.
> Loosen blockformat ID validation to allow for S-ADM frames

- .github/workflows/build.yml
v1 has now been sunset, so we must upgrade.
> Update version of cache action used in CI workflow

- format.sh
Differing clang-format versions on developer machines and CI cause the formatting check to fail. Printing out the version prior to formatting should make the cause of failure more obvious.
> Print clang-format version before performing formatting

- include/adm/private/copy.hpp
- src/elements/audio_programme.cpp
- src/elements/position.cpp
- src/private/rapidxml_wrapper.cpp
This was causing formatting issues as they were mistaken for braced initialisers, and it made the code harder to read for humans too.
> Remove redundant semicolons after constructor bodies
